refactor: improve library verification logic in arcade.yml

diff --git a/.github/workflows/arcade.yml b/.github/workflows/arcade.yml
--- a/.github/workflows/arcade.yml
+++ b/.github/workflows/arcade.yml
@@ -44,12 +44,13 @@ jobs:
           fi
       - name: "Verify Graphic Libraries Presence"
         run: |
-          if [[ -f lib/arcade_sdl2.so && -f lib/arcade_sfml.so ]]; then
-            echo "All libraries exist."
-          else
-            echo "One or more libraries don't exist."
-            exit 1
-          fi
+          for lib in lib/arcade_sdl2.so lib/arcade_sfml.so; do
+              if [[ ! -f "$lib" ]]; then
+                echo "Missing library: $lib"
+                exit 1
+              fi
+          done
+          echo "All libraries exist."
 
   push_to_mirror:
     needs: check_program_compilation
